name: deeptrainfront
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  go_router: ^10.0.0
  provider: ^6.1.1
  fl_chart: ^0.65.0
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.2
  web_socket_channel: ^3.0.3
  flutter_riverpod: ^2.6.1
  lottie: ^3.0.0
  dio: ^5.4.0
  uuid: ^4.5.1
  file_picker: ^8.2.0
  path_provider: ^2.1.5
  webview_flutter: ^4.2.2
  speech_to_text: ^6.6.2
  flutter_tts: ^4.2.3
  video_player: ^2.8.3
  jwt_decoder: ^2.0.1


  



  http: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_lints: ^6.0.0

  mockito: any
flutter:
  uses-material-design: true

  assets:
    - assets/images/
   
