name: Build and Push Flutter Web to ECR

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.0'  # or your desired version
        channel: stable
    - name: Verify Dart Version
      run: dart --version
    - name: Install dependencies
      run: flutter pub get

    - name: Build Flutter Web
      run: flutter build web

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::536284936847:role/deeptrain
        aws-region: us-east-1

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker Image
      run: |
        docker build -t flutter-web-app .
        docker tag flutter-web-app:latest 536284936847.dkr.ecr.us-east-1.amazonaws.com/flutter-web-app:latest

    - name: Push to ECR
      run: |
        docker push 536284936847.dkr.ecr.us-east-1.amazonaws.com/flutter-web-app:latest
